module.exports = [{
    name: 'index',
    path: 'index/Index.jsx',
    title: '首页',
    keywords: '首页,xxx',
    description: '这是我们的首页'
}, {
    name: 'antd',
    path: 'antd/Index.jsx',
    title: '测试',
    keywords: 'antd测试',
    description: '这是antd测试页面'
}, {
    name: 'download',
    path: 'download/Index.jsx',
    title: '下载',
    keywords: 'davao 下载',
    description: '这是下载页面'
}, {
    name: 'rule-service',
    path: 'rule-service/Index.jsx',
    title: '服务条款',
    keywords: '服务条款',
    description: '这是服务条款页面'
}, {
    name: 'rule-manage',
    path: 'rule-manage/Index.jsx',
    title: '管理规则',
    keywords: '管理规则',
    description: '这是管理规则页面'
}, {
    name: 'rule-rate',
    path: 'rule-rate/Index.jsx',
    title: '费率说明',
    keywords: '费率说明',
    description: '这是费率说明页面'
}, {
    name: 'help',
    path: 'help/Index.jsx',
    title: '帮助中心',
    keywords: '帮助中心',
    description: '这是帮助中心页面'
}, {
    name: 'help-more',
    path: 'help-more/Index.jsx',
    title: '帮助中心',
    keywords: '帮助中心',
    description: '这是帮助中心页面'
}, {
    name: 'help-detail',
    path: 'help-detail/Index.jsx',
    title: '帮助中心',
    keywords: '帮助中心',
    description: '这是帮助中心页面'
}, {
    name: 'help-search',
    path: 'help-search/Index.jsx',
    title: '帮助中心',
    keywords: '帮助中心',
    description: '这是帮助中心页面'
}, {
    name: 'news',
    path: 'news/Index.jsx',
    title: '新闻公告',
    keywords: '新闻公告',
    description: '这是新闻公告页面'
}, {
    name: 'news-more',
    path: 'news-more/Index.jsx',
    title: '新闻公告',
    keywords: '新闻公告',
    description: '这是新闻公告页面'
}, {
    name: 'news-detail',
    path: 'news-detail/Index.jsx',
    title: '新闻公告',
    keywords: '新闻公告',
    description: '这是新闻公告页面'
}, {
    name: 'news-search',
    path: 'news-search/Index.jsx',
    title: '新闻公告',
    keywords: '新闻公告',
    description: '这是新闻公告页面'
}, {
    name: 'login',
    path: 'login/Index.jsx',
    title: '登录',
    keywords: '登录',
    description: '这是登录页面'
}, {
    name: 'register',
    path: 'register/Index.jsx',
    title: '注册',
    keywords: '注册',
    description: '这是注册页面'
}, {
    name: 'auth',
    path: 'auth/Index.jsx',
    title: '认证',
    keywords: '认证',
    description: '这是认证页面'
}, {
    name: 'user',
    path: 'user/Index.jsx',
    title: '个人中心',
    keywords: '个人中心',
    description: '这是个人中心页面'
}, {
    name: 'deal',
    path: 'deal/Index.jsx',
    title: '币币交易',
    keywords: '币币交易',
    description: '这是币币交易页面'
}, {
    name: 'recharge',
    path: 'recharge/Index.jsx',
    title: '充值',
    keywords: '充值'
}, {
    name: 'withdraw',
    path: 'withdraw/Index.jsx',
    title: '提现',
    keywords: '提现'
}, {
    name: 'feedback',
    path: 'feedback/Index.jsx',
    title: '意见反馈',
    keywords: '意见反馈'
}, {
    name: 'validate-code',
    path: 'validate-code/Index.jsx',
    title: '验证码',
    keywords: '验证码'
}]